### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by josteink** [josteink/autoarchiver#5]
Implement a .travis.yml file which includes the following:

- configures vm with python 3 and other required modules. 
- runs build and unit-tests (i.e. “make all”)

**Comment by kobim** [comment]
(And don't forget to toggle on your repository at travis-ci.org ...)

**Comment by josteink** [comment]
Indeed and done.

If you want another PR, feel free to add a Travis-badge to the readme :)

**Comment by kobim** [comment]
I actually forgot this in the original PR, but I'll leave this to you.
